# roles/role_lamp/tasks/php.yml
---
- name: 删除旧版本 PHP packages
  yum:
    name: php*
    state: absent


- name: 安装 Remi 仓库
  yum:
    name: http://rpms.remirepo.net/enterprise/remi-release-7.rpm
    state: present

- name: Enable PHP 7.4 Remi repository
  shell: yum-config-manager --enable remi-php74

- name: 安装 PHP and required extensions
  yum:
    name:
      - php
      - php-mysql
      - php-gd
      - php-xml
      - php-mbstring
      - php-cli
      - php-fpm
      - php-opcache
    state: present
    enablerepo: "remi-php74"

- name: Restart Apache
  service:
    name: httpd
    state: restarted
